In [7]:
import pandas as pd
list = [1,2,'Alice',45,[23,34]]
pd_series=pd.Series(list)
pd_shape=pd_series.shape
print(pd_series)
print("Series shape",pd_shape)

0           1
1           2
2       Alice
3          45
4    [23, 34]
dtype: object
Series shape (5,)


In [29]:
import pandas as pd
dict = {'name':"Alice",'age':22,'city':'Mountain'}
df = pd.DataFrame(dict,index=[1])
print(df)
print()
another_dict = {'name':["John","Philip"],'age':22,'city':['Mountain','Philosophy']}
another_df = pd.DataFrame(another_dict)
df_shape=another_df.shape
print(another_df)
print("Df shape",df_shape)
print()
#Select rows and columns
print("Column and rows selection")
name_column=another_df.loc[1,'age']
print(name_column)

    name  age      city
1  Alice   22  Mountain

     name  age        city
0    John   22    Mountain
1  Philip   22  Philosophy
Df shape (2, 3)

Column and rows selection
22


In [43]:
import pandas as pd
url ="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
columns = ['sepal_length','sepal_width','petal_length','petal_width','species']
csv =pd.read_csv(url)
df=pd.DataFrame(csv.values,columns=columns)
print(df.head())
print(df.info())
print()

# Set and reset index
df.set_index('sepal_length',inplace=True)
df.reset_index(inplace=True)
df.set_index(['sepal_length','sepal_width'],inplace=True)
print(df.head())

  sepal_length sepal_width petal_length petal_width      species
0          4.9         3.0          1.4         0.2  Iris-setosa
1          4.7         3.2          1.3         0.2  Iris-setosa
2          4.6         3.1          1.5         0.2  Iris-setosa
3          5.0         3.6          1.4         0.2  Iris-setosa
4          5.4         3.9          1.7         0.4  Iris-setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   sepal_length  149 non-null    object
 1   sepal_width   149 non-null    object
 2   petal_length  149 non-null    object
 3   petal_width   149 non-null    object
 4   species       149 non-null    object
dtypes: object(5)
memory usage: 5.9+ KB
None

                         petal_length petal_width      species
sepal_length sepal_width                                      
4.9          3.0                  1.4   

In [14]:
import pandas as pd
url ="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
columns = ['sepal_length','sepal_width','petal_length','petal_width','species']
csv =pd.read_csv(url)
df=pd.DataFrame(csv.values,columns=columns)
print("Iris species of type Iris-setosa")
print(df[df['species']=='Iris-setosa'].head())
print("Iris with a sepal lenght less than 4.5")
print(df[df['sepal_length']<4.5])

print("Multiply the column sepal lenght values by 2")
df['sepal_length']=df['sepal_length'].astype(int)
mapped_df = df.apply(lambda x: x*2)
print(mapped_df.head())
print("\n Missing values handles")
df_copy = df.copy()
print(df_copy.dropna(subset=['sepal_length']))
saved=df.to_csv("saved.csv")
print("\n Saved saved file")
print(saved)
print()

Iris species of type Iris-setosa
  sepal_length sepal_width petal_length petal_width      species
0          4.9         3.0          1.4         0.2  Iris-setosa
1          4.7         3.2          1.3         0.2  Iris-setosa
2          4.6         3.1          1.5         0.2  Iris-setosa
3          5.0         3.6          1.4         0.2  Iris-setosa
4          5.4         3.9          1.7         0.4  Iris-setosa
Iris with a sepal lenght less than 4.5
   sepal_length sepal_width petal_length petal_width      species
7           4.4         2.9          1.4         0.2  Iris-setosa
12          4.3         3.0          1.1         0.1  Iris-setosa
37          4.4         3.0          1.3         0.2  Iris-setosa
41          4.4         3.2          1.3         0.2  Iris-setosa
Multiply the column sepal lenght values by 2
   sepal_length sepal_width petal_length petal_width                 species
0             8         6.0          2.8         0.4  Iris-setosaIris-setosa
1        

In [68]:
import pandas as pd
url ="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
columns = ['sepal_length','sepal_width','petal_length','petal_width','species']
csv =pd.read_csv(url)
df=pd.DataFrame(csv.values,columns=columns)
sort_df = df.sort_values(by='sepal_length')
print(sort_df.head())

   sepal_length sepal_width petal_length petal_width      species
12          4.3         3.0          1.1         0.1  Iris-setosa
41          4.4         3.2          1.3         0.2  Iris-setosa
37          4.4         3.0          1.3         0.2  Iris-setosa
7           4.4         2.9          1.4         0.2  Iris-setosa
40          4.5         2.3          1.3         0.3  Iris-setosa


In [25]:
import numpy as np
array = np.array([
    [1,2,3,4],
[5,6,7,8],
[9,10,11,12],])
X= array[:,np.newaxis]
Y= array[np.newaxis,:]
print(X)
print()
print(Y)
Z = X-Y
print()
print("Difference ",Z)
print()
sum = np.sum(Z**2,axis=0)
print("Sum",sum)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

Difference  [[[ 0  0  0  0]
  [-4 -4 -4 -4]
  [-8 -8 -8 -8]]

 [[ 4  4  4  4]
  [ 0  0  0  0]
  [-4 -4 -4 -4]]

 [[ 8  8  8  8]
  [ 4  4  4  4]
  [ 0  0  0  0]]]

Sum [[80 80 80 80]
 [32 32 32 32]
 [80 80 80 80]]


In [11]:
import pandas as pd
import numpy as np

# Create sample data
data = {
'Department': ['Engineering', 'Marketing', 'Engineering', 'Sales',
'Marketing', 'Engineering', 'Sales', 'Marketing'],
'Employee': ['Alice', 'Bob', 'Charlie', 'David',
'Eve', 'Frank', 'Grace', 'Henry'],
'Salary': [70000, 65000, 80000, 60000, 68000, 75000, 62000, 70000],
'Years': [2, 5, 8, 3, 6, 4, 2, 7]
}
df = pd.DataFrame(data)
print("Original Data Frame")
print(df)
print()
print("Group By department")
print(df.groupby('Department').describe())
print()
print("Aggregation Operations")
group_by_years=df.groupby('Years')

print("Minimum Year Value")
print(group_by_years.agg('min'))

print("\nMaximum Year Value")
print(group_by_years.agg('max'))

print("\nList of aggregate operations  columns")
print(group_by_years.agg(['min','max']))

print("\nMultiple aggregations for multiple columns")
agg_dict={
    'Department':['min','max'],
    'Salary':['sum','mean'],
}
print(group_by_years.agg(agg_dict))
df['Experience'] = pd.cut(
    df['Years'],
    bins=[0,3,6,10],
    labels=['junior','Mid','senior']
)
print("\n",df)

Original Data Frame
    Department Employee  Salary  Years
0  Engineering    Alice   70000      2
1    Marketing      Bob   65000      5
2  Engineering  Charlie   80000      8
3        Sales    David   60000      3
4    Marketing      Eve   68000      6
5  Engineering    Frank   75000      4
6        Sales    Grace   62000      2
7    Marketing    Henry   70000      7

Group By department
            Salary                                                        \
             count          mean          std      min      25%      50%   
Department                                                                 
Engineering    3.0  75000.000000  5000.000000  70000.0  72500.0  75000.0   
Marketing      3.0  67666.666667  2516.611478  65000.0  66500.0  68000.0   
Sales          2.0  61000.000000  1414.213562  60000.0  60500.0  61000.0   

                              Years                                            \
                 75%      max count      mean       std  min   25%  50

In [21]:
import pandas as pd
employees = pd.DataFrame({
    'EmployeeID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'DeptID': [101, 102, 101, 103]
})

departments = pd.DataFrame({
    'DeptID': [101, 102, 103],
    'Department': ['Engineering', 'Marketing', 'Sales']
})
# merging dataframes
inner_merge = pd.merge(employees,departments,on='DeptID')
print("\nInner Join")
print(inner_merge)
#left Join
new_employee = pd.DataFrame(
    {
        'EmployeeID':[5],
        'Name':['Greg'],
        'DeptID':[105]
    }
)
all_employees = pd.concat([employees,new_employee],ignore_index=True)
merged_left = pd.merge(all_employees,departments,how='right',on='DeptID')
print(merged_left)


Inner Join
   EmployeeID     Name  DeptID   Department
0           1    Alice     101  Engineering
1           2      Bob     102    Marketing
2           3  Charlie     101  Engineering
3           4    David     103        Sales
   EmployeeID     Name  DeptID   Department
0           1    Alice     101  Engineering
1           3  Charlie     101  Engineering
2           2      Bob     102    Marketing
3           4    David     103        Sales
