In [1]:
import torch
x =torch.tensor([2.0,3.0],requires_grad=True) # Tracks  operations for automatic gradients computations

y=x**2
z=sum(y)
z.backward()
print("Autograd")
print(x.grad)

print("Simulation of a linear layer + MSE")
torch.manual_seed(42)
W=torch.rand(3,2,requires_grad=True)
b=torch.rand(2,requires_grad=True)
X=torch.rand(5,3)
y_true=torch.rand(5,2)
print("\nBefore Autograd")
print(W)
print(b)
y_pred = X @ W + b
loss = ((y_pred-y_true)**2).mean()
print(f"Loss: {loss}")
backward=loss.backward()
print(f"Loss backward: {backward}")
print("After Autograd")
print(W.grad)
print(b.grad)


Autograd
tensor([4., 6.])
Simulation of a linear layer + MSE

Before Autograd
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]], requires_grad=True)
tensor([0.2566, 0.7936], requires_grad=True)
Loss: 1.9500236511230469
Loss backward: None
After Autograd
tensor([[0.5983, 1.1093],
        [0.4290, 0.7145],
        [0.6429, 1.1642]])
tensor([0.9530, 1.6033])


In [2]:
# Gradient Management
print("Gradient Management")
print("="*70)
# Gradients accumulate by default
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
# First backward
y1 = (x ** 2).sum()
y1.backward()
print(f"After first backward: x.grad = {x.grad}")
# Second backward - gradients accumulate!
y2 = (x ** 2).sum()
y2.backward()
print(f"After second backward: x.grad = {x.grad} (accumulated!)")
# Must zero gradients before each iteration
x.grad.zero_()  # Zero the gradient
y3 = (x ** 2).sum()
y3.backward()
print(f"After zeroing and backward: x.grad = {x.grad}")

# Detaching tensors
print("\n" + "="*70)
print("Detaching and no_grad:")
a = torch.tensor([1.0, 2.0], requires_grad=True)
b = a * 2
c = b.detach()  # Detach from computation graph
print(f"b.requires_grad: {b.requires_grad}")
print(f"c.requires_grad: {c.requires_grad} (detached)")

Gradient Management
After first backward: x.grad = tensor([2., 4., 6.])
After second backward: x.grad = tensor([ 4.,  8., 12.]) (accumulated!)
After zeroing and backward: x.grad = tensor([2., 4., 6.])

Detaching and no_grad:
b.requires_grad: True
c.requires_grad: False (detached)


In [4]:
import torch.nn as nn
class Linear(nn.Module):
    def __init__(self,input_size,output_size):
        super().__init__()
        self.linear = nn.Linear(input_size,output_size)
    def forward(self,x):
        return self.linear(x)

l_model = Linear(5,2)
x= torch.rand(10,5)
y_pred=l_model.forward(x)
print(y_pred.shape)
# print("Data: ",x)
# print("\nPredicted Values:")
# print(y_pred)
# nn.Dropout(0.2)

print(torch.cuda.is_available())

torch.Size([10, 2])
False
